name: Build Awery Preview App

permissions:
  contents: write

on:
  schedule:
    - cron: '0 6 * * 2'
  workflow_dispatch:

jobs:
  check-updates:
    runs-on: ubuntu-latest
    env:
      CI: true
    outputs:
      SHOULD_RUN: ${{ steps.compare.outputs.SHOULD_RUN }}
      LATEST_SHA: ${{ steps.compare.outputs.LATEST_SHA }}
      LAST_SHA: ${{ steps.compare.outputs.LAST_SHA }}

    steps:
      - name: Checkout Repository
        run: |
          rm -rf * .[^.] .??*
          git clone --branch master https://github.com/MrBoomDeveloper/Awery.git .

      - name: Download last SHA artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          repo: 'itsmechinmoy/awery-updater'
          workflow: release.yml
          name: last-sha
          path: .
          allow-forks: true
        continue-on-error: true
        env:
          DEBUG_MESSAGE: "No previous last-sha artifact found. This is expected on the first run or if previous runs failed."

      - name: Debug Missing Artifact
        run: |
          if [ ! -f last_sha.txt ]; then
            echo "$DEBUG_MESSAGE"
          fi

      - name: Check for updates
        id: compare
        run: |
          LATEST_SHA=$(git rev-parse HEAD)
          echo "Latest commit SHA: $LATEST_SHA"
          echo "LATEST_SHA=${LATEST_SHA}" >> $GITHUB_OUTPUT

          if [ -f last_sha.txt ]; then
            LAST_SHA=$(cat last_sha.txt)
            echo "Last saved commit SHA: $LAST_SHA"
            echo "LAST_SHA=${LAST_SHA}" >> $GITHUB_OUTPUT
          else
            LAST_SHA=""
            echo "No previous SHA found."
            echo "LAST_SHA=${LAST_SHA}" >> $GITHUB_OUTPUT
          fi

          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "Manual trigger detected. Forcing build."
            echo "SHOULD_RUN=true" >> $GITHUB_OUTPUT
          elif [ "$LATEST_SHA" == "$LAST_SHA" ]; then
            echo "No updates found. Canceling the workflow."
            echo "SHOULD_RUN=false" >> $GITHUB_OUTPUT
          else
            echo "Updates found. Continuing workflow."
            echo "SHOULD_RUN=true" >> $GITHUB_OUTPUT
          fi

      - name: Save Current SHA for Next Run
        run: git rev-parse HEAD > last_sha.txt

      - name: Upload Current SHA as an Artifact
        uses: actions/upload-artifact@v4
        with:
          name: last-sha
          path: last_sha.txt

  build:
    runs-on: ubuntu-latest
    needs: check-updates
    if: ${{ needs.check-updates.outputs.SHOULD_RUN == 'true' }}
    env:
      CI: true
      SKIP_BUILD: false

    steps:
      - name: Checkout Repository
        run: |
          rm -rf * .[^.] .??*
          git clone --branch master https://github.com/MrBoomDeveloper/Awery.git .

      - name: Get Commits Since Last Run
        run: |
          if [ "${{ needs.check-updates.outputs.LAST_SHA }}" != "" ]; then
            LAST_SHA=${{ needs.check-updates.outputs.LAST_SHA }}
          else
            LAST_SHA=$(git rev-list --max-parents=0 HEAD)
          fi
          echo "Commits since $LAST_SHA:"
          REPO_URL="https://github.com/MrBoomDeveloper/Awery"
          COMMIT_LOGS=$(git log $LAST_SHA..HEAD --pretty=format:"● %s ~%an [֍](${REPO_URL}/commit/%H)" --max-count=10)
          if [ -z "$COMMIT_LOGS" ]; then
            COMMIT_LOGS="● No new commits since last release"
          fi
          echo "REPO_URL=${REPO_URL}" >> $GITHUB_ENV
          COMMIT_LOGS=$(echo "$COMMIT_LOGS" | sed -E "s@#([0-9]+)@[#\1](${REPO_URL}/pull/\1)@g")
          echo -e "Commits:\n" > commit_log.txt
          echo "$COMMIT_LOGS" | sed 's/●/\n●/g' | sed '/^$/d' >> commit_log.txt
          echo "Raw COMMIT_LOGS:"
          cat commit_log.txt
        shell: bash
        env:
          CI: true
        continue-on-error: true

      - name: Set variables
        run: |
          VER=$(grep -E -o "versionName \".*\"" app/build.gradle | sed -e 's/versionName //g' | tr -d '"')
          SHA=${{ github.sha }}
          VERSION="$VER+${SHA:0:7}"
          echo "Version $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Add Split APK Configuration
        if: ${{ env.SKIP_BUILD != 'true' }}
        run: |
          echo "Adding split APK configuration to build.gradle..."
          if ! grep -q "splits {" app/build.gradle; then
            sed -i '/android {/a\
            \    splits {\
            \        abi {\
            \            enable true\
            \            reset()\
            \            include "armeabi-v7a", "arm64-v8a", "x86", "x86_64"\
            \            universalApk true\
            \        }\
            \    }' app/build.gradle
            echo "Split APK configuration added successfully"
          else
            echo "Splits block already exists in build.gradle"
          fi
          echo "Modified build.gradle android block:"
          sed -n '/android {/,/^}/p' app/build.gradle | head -20

      - name: List files in the directory
        run: ls -l

      - name: Setup JDK 17
        if: ${{ env.SKIP_BUILD != 'true' }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: gradle

      - name: Decode Keystore File
        if: ${{ env.SKIP_BUILD != 'true' }}
        run: echo "${{ secrets.KEYSTORE_FILE }}" | base64 -d > $GITHUB_WORKSPACE/key.keystore

      - name: Make gradlew executable
        if: ${{ env.SKIP_BUILD != 'true' }}
        run: chmod +x ./gradlew

      - name: Build with Gradle
        if: ${{ env.SKIP_BUILD != 'true' }}
        run: |
          ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file=$GITHUB_WORKSPACE/key.keystore \
            -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} \
            -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} \
            -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}

      - name: Verify APK Output
        if: ${{ env.SKIP_BUILD != 'true' }}
        run: |
          echo "Listing all APK files in app/build/outputs/apk/release:"
          ls -la app/build/outputs/apk/release/
          
          if [ -f app/build/outputs/apk/release/app-universal-release.apk ]; then
            echo "✅ Universal APK found (app-universal-release.apk)"
            echo "UNIVERSAL_APK_EXISTS=true" >> $GITHUB_ENV
            echo "UNIVERSAL_APK_NAME=app-universal-release.apk" >> $GITHUB_ENV
          elif [ -f app/build/outputs/apk/release/app-release.apk ]; then
            echo "✅ Universal APK found (app-release.apk)"
            echo "UNIVERSAL_APK_EXISTS=true" >> $GITHUB_ENV
            echo "UNIVERSAL_APK_NAME=app-release.apk" >> $GITHUB_ENV
          else
            echo "❌ Universal APK not found!"
            echo "UNIVERSAL_APK_EXISTS=false" >> $GITHUB_ENV
          fi
          
          SPLIT_APKS=$(find app/build/outputs/apk/release/ -name "app-*-release.apk" ! -name "app-universal-release.apk" ! -name "app-release.apk" 2>/dev/null || true)
          if [ -n "$SPLIT_APKS" ]; then
            echo "✅ Split APKs found:"
            echo "$SPLIT_APKS" | while read apk; do
              echo "  - $(basename "$apk")"
            done
            echo "SPLIT_APKS_EXIST=true" >> $GITHUB_ENV
          else
            echo "❌ No split APKs found"
            echo "SPLIT_APKS_EXIST=false" >> $GITHUB_ENV
          fi

      - name: Calculate SHA256 Checksums and Set Environment Variables
        if: ${{ env.SKIP_BUILD != 'true' }}
        run: |
          echo "Calculating SHA256 checksums for APKs..."
          
          if [ "$UNIVERSAL_APK_EXISTS" = "true" ]; then
            UNIVERSAL_SHA=$(sha256sum "app/build/outputs/apk/release/$UNIVERSAL_APK_NAME" | cut -d ' ' -f 1)
            echo "APK_UNIVERSAL_SHA=${UNIVERSAL_SHA}" >> $GITHUB_ENV
            echo "Universal APK SHA256: ${UNIVERSAL_SHA}"
          fi
          
          if [ "$SPLIT_APKS_EXIST" = "true" ]; then
            echo "Split APK checksums:"
            find app/build/outputs/apk/release/ -name "app-*-release.apk" ! -name "app-universal-release.apk" ! -name "app-release.apk" | while read apk; do
              BASENAME=$(basename "$apk" .apk)
              ABI=$(echo "$BASENAME" | sed 's/app-//' | sed 's/-release//')
              SHA=$(sha256sum "$apk" | cut -d ' ' -f 1)
              echo "APK_${ABI^^}_SHA=${SHA}" >> $GITHUB_ENV
              echo "${ABI} APK SHA256: ${SHA}"
            done
          fi

      - name: Append Checksums to Commit Log
        if: ${{ env.SKIP_BUILD != 'true' }}
        run: |
          echo -e "\n---\n" >> commit_log.txt
          echo -e "### Checksums\n" >> commit_log.txt
          echo "| Variant | SHA-256 |" >> commit_log.txt
          echo "| ------- | ------- |" >> commit_log.txt
          
          if [ "$UNIVERSAL_APK_EXISTS" = "true" ]; then
            echo "| Universal | ${{ env.APK_UNIVERSAL_SHA }} |" >> commit_log.txt
          fi
          
          if [ "$SPLIT_APKS_EXIST" = "true" ]; then
            find app/build/outputs/apk/release/ -name "app-*-release.apk" ! -name "app-universal-release.apk" ! -name "app-release.apk" | while read apk; do
              BASENAME=$(basename "$apk" .apk)
              ABI=$(echo "$BASENAME" | sed 's/app-//' | sed 's/-release//')
              SHA=$(sha256sum "$apk" | cut -d ' ' -f 1)
              echo "| ${ABI} | ${SHA} |" >> commit_log.txt
            done
          fi
          
          echo "Updated commit_log.txt with checksums:"
          cat commit_log.txt
        shell: bash

      - name: Upload APKs as Build Artifacts
        if: ${{ env.SKIP_BUILD != 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: Awery-APKs
          retention-days: 5
          compression-level: 9
          path: |
            app/build/outputs/apk/release/*.apk

      - name: Create GitHub Release and Upload Assets
        if: ${{ env.SKIP_BUILD != 'true' }}
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ env.VERSION }}
          name: Awery v${{ env.VERSION }}
          bodyFile: commit_log.txt
          artifacts: app/build/outputs/apk/release/*.apk
          draft: true
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Commit Log as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: commit-log
          path: commit_log.txt
